image: barichello/godot-ci:3.4

cache:
  key: import-assets
  paths:
    - .import/

test:
  stage: test
  script:
    - godot goldenGadget/GGTestsRunner.tscn

pages:
  script:
    - mkdir public
    - cp -r docs/dist/* docs/assets/* public
  artifacts:
    paths:
      - public
  only:
    - master
