image: codedarigan/godot_headless_ci:latest

test:
  stage: test
  script:
    - godot goldenGadget/GGTestsRunner.tscn

pages:
  script:
    - mkdir public
    - cp -r docs/dist/* docs/assets/* public
  artifacts:
    paths:
      - public
  only:
    - master
